### PR TITLE
Clean up infra agent support submission from gboie

### PR DESCRIPTION
**Pull request by fightingmonk**
This is a continuation of @gabrielnewrelic 's PR #43 that adds support for New Relic Infrastructure agents. There are some performance issues when adding that much new data, and I need to refactor some core logic to fix them. So... rather than fixing those on main and then asking him to update all of his improvements, I'm forking his fork.

### CODE REVIEW

**Comment by jpvajda** [comment]
@fightingmonk is this stale at this point or do you still intend to make this change?

**Comment by fightingmonk** [comment]
> is this stale at this point or do you still intend to make this change?
@jpvajda still intending to complete this when time permits.

**Comment by jpvajda** [comment]
@fightingmonk just checking in on this PR again, are you intending on merging it soon?

**Comment by jpvajda** [comment]
closing due to PR age.

**Pull request closed without merging**
