### PR TITLE
feat: add new icon to agent groundskeeper nerdpack

### PR DESCRIPTION
**Pull request by MattIGolden**
Hey, I saw there was an open issue (#30) for this icon. I created a couple of options I hope they’re helpful: 
- This is a concept of a shovel and an update or refresh icon put together. 
icon-2

- This is a zen garden rake leaving marks in the sand. 
icon-3

The shovel icon, I believe, is the strongest choice because it is straightforward and is the most clear at smaller sizes.

### CODE REVIEW

**Comment by tangollama** [comment]
Thanks @MattIGolden for the PR. Great stuff! Personally, I prefer the zen rake. @danielgolden, @fightingmonk, what's your review?

**Comment by danielgolden** [comment]
@MattIGolden It looks like the icon your recommending (based on the file you changed) is this one. Is that true?
icon

@tangollama imo it's between the above shovel icon and the rake (though, unless you know what you're looking at, users may not see a rake when they look at the icon), though curious to hear what @fightingmonk thinks.

**Comment by fightingmonk** [comment]
Nice, thanks @MattIGolden 
I agree w/ @danielgolden  that the version of a shovel in your PR is the most recognizable. Once you've signed the CLA I'm happy to accept it.

**Comment by MattIGolden** [comment]
@tangollama Thank you, it's my pleasure!
@danielgolden yes, the shovel icon is the one I'm recommending.
@fightingmonk Thank you, I agree with Daniel as well. I signed the CLA yesterday, but I seemed to have used the wrong email. I have attempted to re-sign using the correct email, but the document is now locked in with my initial information. I have also added the correct email to my account as suggested. So it is now pending approval.

**Comment by fightingmonk** [comment]
Per @tangollama CLA is signed.

**Pull request merged**
